// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoeStore.Infrastructure.Persistence;

#nullable disable

namespace ShoeStore.Infrastructure.Migrations
{
    [DbContext(typeof(ShoeStoreDbContext))]
    partial class ShoeStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CartId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("OldValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long?>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Brands", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<byte?>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.HasIndex("StoreId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Code = "PRODUCT_VIEW",
                            Description = "View products"
                        },
                        new
                        {
                            Id = 11,
                            Code = "PRODUCT_CREATE",
                            Description = "Create product"
                        },
                        new
                        {
                            Id = 12,
                            Code = "PRODUCT_UPDATE",
                            Description = "Update product"
                        },
                        new
                        {
                            Id = 13,
                            Code = "PRODUCT_DELETE",
                            Description = "Delete product"
                        },
                        new
                        {
                            Id = 57,
                            Code = "PRODUCT_SEARCH",
                            Description = "Search products"
                        },
                        new
                        {
                            Id = 58,
                            Code = "PRODUCT_SUGGEST",
                            Description = "Suggest product keywords"
                        },
                        new
                        {
                            Id = 59,
                            Code = "PRODUCT_STORE_QUANTITY_MANAGE",
                            Description = "Manage product-store quantity"
                        },
                        new
                        {
                            Id = 14,
                            Code = "PROMOTION_VIEW",
                            Description = "View promotions"
                        },
                        new
                        {
                            Id = 15,
                            Code = "PROMOTION_CREATE",
                            Description = "Create promotion"
                        },
                        new
                        {
                            Id = 16,
                            Code = "PROMOTION_UPDATE",
                            Description = "Update promotion"
                        },
                        new
                        {
                            Id = 17,
                            Code = "PROMOTION_DELETE",
                            Description = "Delete promotion"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BRAND_VIEW",
                            Description = "View brands"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BRAND_CREATE",
                            Description = "Create brand"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BRAND_UPDATE",
                            Description = "Update brand"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BRAND_DELETE",
                            Description = "Delete brand"
                        },
                        new
                        {
                            Id = 22,
                            Code = "STORE_VIEW",
                            Description = "View stores"
                        },
                        new
                        {
                            Id = 23,
                            Code = "STORE_CREATE",
                            Description = "Create store"
                        },
                        new
                        {
                            Id = 24,
                            Code = "STORE_UPDATE",
                            Description = "Update store"
                        },
                        new
                        {
                            Id = 25,
                            Code = "STORE_DELETE",
                            Description = "Delete store"
                        },
                        new
                        {
                            Id = 26,
                            Code = "SUPPLIER_VIEW",
                            Description = "View suppliers"
                        },
                        new
                        {
                            Id = 27,
                            Code = "SUPPLIER_CREATE",
                            Description = "Create supplier"
                        },
                        new
                        {
                            Id = 28,
                            Code = "SUPPLIER_UPDATE",
                            Description = "Update supplier"
                        },
                        new
                        {
                            Id = 29,
                            Code = "SUPPLIER_DELETE",
                            Description = "Delete supplier"
                        },
                        new
                        {
                            Id = 30,
                            Code = "RECEIPT_VIEW",
                            Description = "View receipts"
                        },
                        new
                        {
                            Id = 31,
                            Code = "RECEIPT_CREATE",
                            Description = "Create receipt"
                        },
                        new
                        {
                            Id = 32,
                            Code = "RECEIPT_UPDATE",
                            Description = "Update receipt"
                        },
                        new
                        {
                            Id = 33,
                            Code = "RECEIPT_DELETE",
                            Description = "Delete receipt"
                        },
                        new
                        {
                            Id = 34,
                            Code = "ORDER_VIEW",
                            Description = "View orders"
                        },
                        new
                        {
                            Id = 35,
                            Code = "ORDER_CREATE",
                            Description = "Create order"
                        },
                        new
                        {
                            Id = 36,
                            Code = "ORDER_UPDATE",
                            Description = "Update order"
                        },
                        new
                        {
                            Id = 37,
                            Code = "ORDER_DELETE",
                            Description = "Delete order"
                        },
                        new
                        {
                            Id = 60,
                            Code = "ORDER_MANAGE_DETAILS",
                            Description = "Manage order details/status"
                        },
                        new
                        {
                            Id = 38,
                            Code = "NOTIFICATION_VIEW",
                            Description = "View notifications"
                        },
                        new
                        {
                            Id = 39,
                            Code = "NOTIFICATION_CREATE",
                            Description = "Create notification"
                        },
                        new
                        {
                            Id = 40,
                            Code = "NOTIFICATION_DELETE",
                            Description = "Delete notification"
                        },
                        new
                        {
                            Id = 41,
                            Code = "COMMENT_VIEW",
                            Description = "View comments"
                        },
                        new
                        {
                            Id = 42,
                            Code = "COMMENT_CREATE",
                            Description = "Create comment"
                        },
                        new
                        {
                            Id = 43,
                            Code = "COMMENT_UPDATE",
                            Description = "Update comment"
                        },
                        new
                        {
                            Id = 44,
                            Code = "COMMENT_DELETE",
                            Description = "Delete comment"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CART_VIEW",
                            Description = "View cart"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CART_CREATE",
                            Description = "Create/Add to cart"
                        },
                        new
                        {
                            Id = 47,
                            Code = "CART_UPDATE",
                            Description = "Update cart item"
                        },
                        new
                        {
                            Id = 48,
                            Code = "CART_DELETE",
                            Description = "Remove from cart / clear cart"
                        },
                        new
                        {
                            Id = 49,
                            Code = "USER_VIEW",
                            Description = "View users"
                        },
                        new
                        {
                            Id = 50,
                            Code = "USER_CREATE",
                            Description = "Create user"
                        },
                        new
                        {
                            Id = 51,
                            Code = "USER_UPDATE",
                            Description = "Update user"
                        },
                        new
                        {
                            Id = 52,
                            Code = "USER_DELETE",
                            Description = "Delete user"
                        },
                        new
                        {
                            Id = 53,
                            Code = "ROLE_MANAGE",
                            Description = "Manage roles"
                        },
                        new
                        {
                            Id = 54,
                            Code = "PERMISSION_MANAGE",
                            Description = "Manage permissions"
                        },
                        new
                        {
                            Id = 55,
                            Code = "DASHBOARD_VIEW",
                            Description = "View dashboard"
                        },
                        new
                        {
                            Id = 56,
                            Code = "AUDIT_VIEW",
                            Description = "View audit logs"
                        });
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Size")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasFilter("[SKU] IS NOT NULL");

                    b.HasIndex("StatusId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.PromotionProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PromotionId");

                    b.ToTable("PromotionProducts", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.PromotionStore", b =>
                {
                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("PromotionId", "StoreId");

                    b.HasIndex("StoreId");

                    b.ToTable("PromotionStores", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Receipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.HasIndex("StoreId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Receipts", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.ReceiptDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int");

                    b.Property<long>("ReceiptId")
                        .HasColumnType("bigint");

                    b.Property<int?>("ReceivedQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptDetails", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Role", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Code = "SUPER ADMIN",
                            Name = "Super Admin"
                        },
                        new
                        {
                            Id = (byte)2,
                            Code = "ADMIN",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = (byte)3,
                            Code = "STAFF",
                            Name = "Staff"
                        },
                        new
                        {
                            Id = (byte)4,
                            Code = "CUSTOMER",
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.RolePermission", b =>
                {
                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 57
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 58
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 59
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 60
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 38
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 39
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 40
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 41
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 42
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 43
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 44
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 45
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 46
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 47
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 48
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 49
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 50
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 51
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 52
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 53
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 54
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 55
                        },
                        new
                        {
                            RoleId = (byte)1,
                            PermissionId = 56
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 57
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 58
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 59
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 37
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 60
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 38
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 39
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 40
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 41
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 42
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 43
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 44
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 45
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 46
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 47
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 48
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 49
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 50
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 51
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 52
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 53
                        },
                        new
                        {
                            RoleId = (byte)2,
                            PermissionId = 55
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 57
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 58
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 36
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 60
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 41
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 42
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 43
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 45
                        },
                        new
                        {
                            RoleId = (byte)3,
                            PermissionId = 55
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 42
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 45
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 46
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 47
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 48
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = (byte)4,
                            PermissionId = 34
                        });
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("Statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ACTIVE",
                            Description = "Active status",
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Code = "INACTIVE",
                            Description = "Inactive status",
                            Name = "Inactive"
                        },
                        new
                        {
                            Id = 3,
                            Code = "PAYMENT_SUCCESS",
                            Description = "Đơn hàng đã thanh toán thành công",
                            Name = "Thanh toán thành công"
                        },
                        new
                        {
                            Id = 4,
                            Code = "PENDING_CONFIRMATION",
                            Description = "Đơn hàng đang chờ xác nhận",
                            Name = "Chờ xác nhận"
                        },
                        new
                        {
                            Id = 5,
                            Code = "CONFIRMED",
                            Description = "Đơn hàng đã được xác nhận",
                            Name = "Xác nhận"
                        },
                        new
                        {
                            Id = 6,
                            Code = "CANCELLED",
                            Description = "Đơn hàng đã bị hủy",
                            Name = "Đã hủy"
                        });
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.StoreProduct", b =>
                {
                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("StoreId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("StoreProducts", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[Code] IS NOT NULL");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Phone");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.HasIndex("StoreId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 12, 1, 20, 29, 23, 988, DateTimeKind.Local).AddTicks(2974),
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            Gender = 0,
                            PasswordHash = "AQAAAAIAAYagAAAAEJHj9KC5ohdyR9cx+RK/ubS9Ao649iV3L5s9AYGW+ItPmjqAP0reOzoMAsjtJZon4A==",
                            Phone = "0345602265",
                            RoleId = (byte)1,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("CartItem", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Brand", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Status", "Status")
                        .WithMany("Brands")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Cart", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Comment", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Order", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShoeStore.Domain.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("Customer");

                    b.Navigation("Status");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Store", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("StoreId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Product", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShoeStore.Domain.Entities.Status", "Status")
                        .WithMany("Products")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Status");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Promotion", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Status", "Status")
                        .WithMany("Promotions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.PromotionProduct", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Promotion", "Promotion")
                        .WithMany("PromotionProducts")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.PromotionStore", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Promotion", "Promotion")
                        .WithMany("PromotionStores")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Store", "Store")
                        .WithMany("PromotionStores")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Receipt", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Status", "Status")
                        .WithMany("Receipts")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ShoeStore.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Status");

                    b.Navigation("Store");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.ReceiptDetail", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Receipt", "Receipt")
                        .WithMany("ReceiptDetails")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Store", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Status", "Status")
                        .WithMany("Stores")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.StoreProduct", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Product", "Product")
                        .WithMany("StoreProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Store", "Store")
                        .WithMany("StoreProducts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Supplier", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Status", "Status")
                        .WithMany("Suppliers")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.User", b =>
                {
                    b.HasOne("ShoeStore.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Status", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShoeStore.Domain.Entities.Store", "Store")
                        .WithMany("Users")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");

                    b.Navigation("Status");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Promotion", b =>
                {
                    b.Navigation("PromotionProducts");

                    b.Navigation("PromotionStores");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Receipt", b =>
                {
                    b.Navigation("ReceiptDetails");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Status", b =>
                {
                    b.Navigation("Brands");

                    b.Navigation("Orders");

                    b.Navigation("Products");

                    b.Navigation("Promotions");

                    b.Navigation("Receipts");

                    b.Navigation("Stores");

                    b.Navigation("Suppliers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Store", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Orders");

                    b.Navigation("PromotionStores");

                    b.Navigation("StoreProducts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShoeStore.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
